
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\130\000\002\014\003\000\002\002\004\000\002\014" +
    "\005\000\002\004\004\000\002\004\004\000\002\004\002" +
    "\000\002\005\003\000\002\005\003\000\002\006\006\000" +
    "\002\042\011\000\002\043\002\000\002\043\005\000\002" +
    "\010\004\000\002\010\002\000\002\047\003\000\002\047" +
    "\003\000\002\050\003\000\002\050\003\000\002\036\003" +
    "\000\002\036\003\000\002\051\003\000\002\051\003\000" +
    "\002\051\003\000\002\051\003\000\002\052\002\000\002" +
    "\011\012\000\002\053\002\000\002\011\012\000\002\037" +
    "\005\000\002\037\005\000\002\012\004\000\002\012\002" +
    "\000\002\013\004\000\002\013\004\000\002\013\003\000" +
    "\002\013\003\000\002\013\003\000\002\013\005\000\002" +
    "\002\006\000\002\002\005\000\002\002\005\000\002\046" +
    "\007\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\030\003\000\002\030\003\000\002\024\005\000" +
    "\002\024\005\000\002\024\005\000\002\024\005\000\002" +
    "\024\005\000\002\024\003\000\002\024\004\000\002\024" +
    "\005\000\002\032\006\000\002\033\004\000\002\033\002" +
    "\000\002\035\002\000\002\035\005\000\002\035\005\000" +
    "\002\020\005\000\002\020\005\000\002\020\003\000\002" +
    "\021\004\000\002\021\006\000\002\022\004\000\002\022" +
    "\004\000\002\022\004\000\002\022\004\000\002\022\004" +
    "\000\002\022\004\000\002\022\004\000\002\022\004\000" +
    "\002\023\003\000\002\023\003\000\002\054\002\000\002" +
    "\055\002\000\002\015\014\000\002\016\002\000\002\056" +
    "\002\000\002\016\007\000\002\057\002\000\002\017\012" +
    "\000\002\040\002\000\002\040\006\000\002\041\002\000" +
    "\002\041\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\237\000\020\002\ufffc\003\ufffc\004\ufffc\005\ufffc\006" +
    "\ufffc\007\ufffc\043\ufffc\001\002\000\006\002\240\003\237" +
    "\001\002\000\020\002\001\003\001\004\011\005\016\006" +
    "\017\007\012\043\014\001\002\000\020\002\ufffa\003\ufffa" +
    "\004\ufffa\005\ufffa\006\ufffa\007\ufffa\043\ufffa\001\002\000" +
    "\020\002\ufffd\003\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd" +
    "\043\ufffd\001\002\000\004\046\217\001\002\000\004\046" +
    "\uffed\001\002\000\004\046\uffea\001\002\000\020\002\ufffb" +
    "\003\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb\043\ufffb\001" +
    "\002\000\004\046\020\001\002\000\020\002\ufffe\003\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\043\ufffe\001\002\000" +
    "\004\046\uffec\001\002\000\004\046\uffeb\001\002\000\004" +
    "\031\021\001\002\000\004\032\022\001\002\000\004\042" +
    "\023\001\002\000\024\004\uffe7\005\uffe7\006\uffe7\007\uffe7" +
    "\012\uffe7\016\uffe7\041\uffe7\044\uffe7\046\uffe7\001\002\000" +
    "\024\004\uffe2\005\uffe2\006\uffe2\007\uffe2\012\uffe2\016\uffe2" +
    "\041\uffe2\044\uffe2\046\uffe2\001\002\000\024\004\011\005" +
    "\016\006\017\007\012\012\035\016\026\041\040\044\042" +
    "\046\036\001\002\000\004\031\210\001\002\000\004\046" +
    "\204\001\002\000\024\004\uffe3\005\uffe3\006\uffe3\007\uffe3" +
    "\012\uffe3\016\uffe3\041\uffe3\044\uffe3\046\uffe3\001\002\000" +
    "\004\037\203\001\002\000\004\037\202\001\002\000\024" +
    "\004\uffdf\005\uffdf\006\uffdf\007\uffdf\012\uffdf\016\uffdf\041" +
    "\uffdf\044\uffdf\046\uffdf\001\002\000\004\040\200\001\002" +
    "\000\004\031\126\001\002\000\010\031\100\033\077\040" +
    "\101\001\002\000\024\004\uffdd\005\uffdd\006\uffdd\007\uffdd" +
    "\012\uffdd\016\uffdd\041\uffdd\044\uffdd\046\uffdd\001\002\000" +
    "\020\002\uffe6\003\uffe6\004\uffe6\005\uffe6\006\uffe6\007\uffe6" +
    "\043\uffe6\001\002\000\024\004\uffde\005\uffde\006\uffde\007" +
    "\uffde\012\uffde\016\uffde\041\uffde\044\uffde\046\uffde\001\002" +
    "\000\022\020\044\031\050\045\057\046\055\047\043\051" +
    "\047\052\046\053\053\001\002\000\042\010\ufff1\011\ufff1" +
    "\014\ufff1\015\ufff1\017\ufff1\020\ufff1\021\ufff1\022\ufff1\023" +
    "\ufff1\025\ufff1\026\ufff1\027\ufff1\030\ufff1\032\ufff1\036\ufff1" +
    "\037\ufff1\001\002\000\014\020\044\031\050\046\055\047" +
    "\043\051\047\001\002\000\020\017\uffcd\020\uffcd\021\uffcd" +
    "\022\uffcd\023\uffcd\032\uffcd\037\uffcd\001\002\000\014\010" +
    "\uffef\011\uffef\032\uffef\036\uffef\037\uffef\001\002\000\042" +
    "\010\ufff0\011\ufff0\014\ufff0\015\ufff0\017\ufff0\020\ufff0\021" +
    "\ufff0\022\ufff0\023\ufff0\025\ufff0\026\ufff0\027\ufff0\030\ufff0" +
    "\032\ufff0\036\ufff0\037\ufff0\001\002\000\014\020\044\031" +
    "\050\046\055\047\043\051\047\001\002\000\042\010\uffd4" +
    "\011\uffd4\014\uffd4\015\uffd4\017\uffd4\020\uffd4\021\uffd4\022" +
    "\uffd4\023\uffd4\025\uffd4\026\uffd4\027\uffd4\030\uffd4\032\uffd4" +
    "\036\uffd4\037\uffd4\001\002\000\004\037\073\001\002\000" +
    "\014\010\uffee\011\uffee\032\uffee\036\uffee\037\uffee\001\002" +
    "\000\016\017\061\020\064\021\062\022\065\023\060\037" +
    "\063\001\002\000\022\017\uffd3\020\uffd3\021\uffd3\022\uffd3" +
    "\023\uffd3\032\uffd3\036\uffd3\037\uffd3\001\002\000\014\010" +
    "\ufff2\011\ufff2\032\ufff2\036\ufff2\037\ufff2\001\002\000\014" +
    "\010\ufff3\011\ufff3\032\ufff3\036\ufff3\037\ufff3\001\002\000" +
    "\014\020\044\031\050\046\055\047\043\051\047\001\002" +
    "\000\014\020\044\031\050\046\055\047\043\051\047\001" +
    "\002\000\014\020\044\031\050\046\055\047\043\051\047" +
    "\001\002\000\024\004\uffe5\005\uffe5\006\uffe5\007\uffe5\012" +
    "\uffe5\016\uffe5\041\uffe5\044\uffe5\046\uffe5\001\002\000\014" +
    "\020\044\031\050\046\055\047\043\051\047\001\002\000" +
    "\014\020\044\031\050\046\055\047\043\051\047\001\002" +
    "\000\020\017\uffcf\020\uffcf\021\uffcf\022\uffcf\023\uffcf\032" +
    "\uffcf\037\uffcf\001\002\000\020\017\uffd1\020\uffd1\021\062" +
    "\022\065\023\060\032\uffd1\037\uffd1\001\002\000\020\017" +
    "\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\032\uffd0\037\uffd0" +
    "\001\002\000\020\017\uffd2\020\uffd2\021\062\022\065\023" +
    "\060\032\uffd2\037\uffd2\001\002\000\020\017\uffce\020\uffce" +
    "\021\uffce\022\uffce\023\uffce\032\uffce\037\uffce\001\002\000" +
    "\024\004\uffe4\005\uffe4\006\uffe4\007\uffe4\012\uffe4\016\uffe4" +
    "\041\uffe4\044\uffe4\046\uffe4\001\002\000\016\017\061\020" +
    "\064\021\062\022\065\023\060\032\075\001\002\000\020" +
    "\017\uffcb\020\uffcb\021\uffcb\022\uffcb\023\uffcb\032\uffcb\037" +
    "\uffcb\001\002\000\020\017\uffcc\020\uffcc\021\062\022\065" +
    "\023\060\032\uffcc\037\uffcc\001\002\000\004\047\120\001" +
    "\002\000\012\032\uffc8\046\055\047\043\051\047\001\002" +
    "\000\022\020\044\031\050\045\057\046\106\047\043\051" +
    "\047\052\046\053\053\001\002\000\004\037\uffda\001\002" +
    "\000\004\037\uffd6\001\002\000\004\037\uffd5\001\002\000" +
    "\016\017\061\020\064\021\062\022\065\023\060\037\uffd7" +
    "\001\002\000\020\017\uffd3\020\uffd3\021\uffd3\022\uffd3\023" +
    "\uffd3\031\100\037\uffd3\001\002\000\006\032\uffc7\036\112" +
    "\001\002\000\004\032\111\001\002\000\004\037\uffca\001" +
    "\002\000\016\045\057\046\055\047\043\051\047\052\046" +
    "\053\053\001\002\000\004\032\uffc9\001\002\000\006\032" +
    "\uffc7\036\112\001\002\000\006\032\uffc7\036\112\001\002" +
    "\000\004\032\uffc5\001\002\000\004\032\uffc6\001\002\000" +
    "\004\034\121\001\002\000\030\010\ufff7\011\ufff7\014\ufff7" +
    "\015\ufff7\025\ufff7\026\ufff7\027\ufff7\030\ufff7\032\ufff7\033" +
    "\123\040\ufff7\001\002\000\026\010\uffd8\011\uffd8\014\uffd8" +
    "\015\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8\032\uffd8\040" +
    "\uffd8\001\002\000\004\050\124\001\002\000\004\034\125" +
    "\001\002\000\030\010\ufff6\011\ufff6\014\ufff6\015\ufff6\025" +
    "\ufff6\026\ufff6\027\ufff6\030\ufff6\032\ufff6\037\ufff6\040\ufff6" +
    "\001\002\000\012\031\131\046\133\047\043\051\047\001" +
    "\002\000\016\014\162\015\157\025\164\026\161\027\163" +
    "\030\165\001\002\000\024\010\uffb6\011\uffb6\014\uffb6\015" +
    "\uffb6\025\uffb6\026\uffb6\027\uffb6\030\uffb6\032\uffb6\001\002" +
    "\000\010\046\133\047\043\051\047\001\002\000\024\010" +
    "\uffb7\011\uffb7\014\uffb7\015\uffb7\025\uffb7\026\uffb7\027\uffb7" +
    "\030\uffb7\032\uffb7\001\002\000\026\010\uffd3\011\uffd3\014" +
    "\uffd3\015\uffd3\025\uffd3\026\uffd3\027\uffd3\030\uffd3\032\uffd3" +
    "\033\077\001\002\000\010\010\152\011\153\032\uffc2\001" +
    "\002\000\004\032\136\001\002\000\004\042\137\001\002" +
    "\000\024\004\uffb5\005\uffb5\006\uffb5\007\uffb5\012\uffb5\016" +
    "\uffb5\041\uffb5\044\uffb5\046\uffb5\001\002\000\024\004\uffe2" +
    "\005\uffe2\006\uffe2\007\uffe2\012\uffe2\016\uffe2\041\uffe2\044" +
    "\uffe2\046\uffe2\001\002\000\024\004\011\005\016\006\017" +
    "\007\012\012\035\016\026\041\uffb4\044\042\046\036\001" +
    "\002\000\004\041\143\001\002\000\026\004\uffb2\005\uffb2" +
    "\006\uffb2\007\uffb2\012\uffb2\013\144\016\uffb2\041\uffb2\044" +
    "\uffb2\046\uffb2\001\002\000\004\042\146\001\002\000\024" +
    "\004\uffb3\005\uffb3\006\uffb3\007\uffb3\012\uffb3\016\uffb3\041" +
    "\uffb3\044\uffb3\046\uffb3\001\002\000\024\004\uffb1\005\uffb1" +
    "\006\uffb1\007\uffb1\012\uffb1\016\uffb1\041\uffb1\044\uffb1\046" +
    "\uffb1\001\002\000\024\004\uffe2\005\uffe2\006\uffe2\007\uffe2" +
    "\012\uffe2\016\uffe2\041\uffe2\044\uffe2\046\uffe2\001\002\000" +
    "\024\004\011\005\016\006\017\007\012\012\035\016\026" +
    "\041\151\044\042\046\036\001\002\000\024\004\uffb0\005" +
    "\uffb0\006\uffb0\007\uffb0\012\uffb0\016\uffb0\041\uffb0\044\uffb0" +
    "\046\uffb0\001\002\000\012\031\131\046\133\047\043\051" +
    "\047\001\002\000\012\031\131\046\133\047\043\051\047" +
    "\001\002\000\004\032\uffc3\001\002\000\004\032\uffc4\001" +
    "\002\000\016\014\162\015\157\025\164\026\161\027\163" +
    "\030\165\001\002\000\016\045\057\046\133\047\043\051" +
    "\047\052\046\053\053\001\002\000\004\032\174\001\002" +
    "\000\010\046\133\047\043\051\047\001\002\000\016\045" +
    "\057\046\133\047\043\051\047\052\046\053\053\001\002" +
    "\000\010\046\133\047\043\051\047\001\002\000\010\046" +
    "\133\047\043\051\047\001\002\000\010\046\133\047\043" +
    "\051\047\001\002\000\010\010\uffba\011\uffba\032\uffba\001" +
    "\002\000\010\010\uffbd\011\uffbd\032\uffbd\001\002\000\010" +
    "\010\uffbb\011\uffbb\032\uffbb\001\002\000\010\010\uffbf\011" +
    "\uffbf\032\uffbf\001\002\000\010\010\uffb8\011\uffb8\032\uffb8" +
    "\001\002\000\010\010\uffbc\011\uffbc\032\uffbc\001\002\000" +
    "\010\010\uffc0\011\uffc0\032\uffc0\001\002\000\010\010\uffbe" +
    "\011\uffbe\032\uffbe\001\002\000\010\010\uffb9\011\uffb9\032" +
    "\uffb9\001\002\000\010\010\uffc1\011\uffc1\032\uffc1\001\002" +
    "\000\022\020\044\031\050\045\057\046\106\047\043\051" +
    "\047\052\046\053\053\001\002\000\004\037\uffd9\001\002" +
    "\000\024\004\uffe1\005\uffe1\006\uffe1\007\uffe1\012\uffe1\016" +
    "\uffe1\041\uffe1\044\uffe1\046\uffe1\001\002\000\024\004\uffe0" +
    "\005\uffe0\006\uffe0\007\uffe0\012\uffe0\016\uffe0\041\uffe0\044" +
    "\uffe0\046\uffe0\001\002\000\006\037\205\040\206\001\002" +
    "\000\024\004\uffdc\005\uffdc\006\uffdc\007\uffdc\012\uffdc\016" +
    "\uffdc\041\uffdc\044\uffdc\046\uffdc\001\002\000\022\020\044" +
    "\031\050\045\057\046\106\047\043\051\047\052\046\053" +
    "\053\001\002\000\004\037\uffdb\001\002\000\012\031\131" +
    "\046\133\047\043\051\047\001\002\000\004\032\212\001" +
    "\002\000\004\042\uffaf\001\002\000\004\042\214\001\002" +
    "\000\024\004\uffe2\005\uffe2\006\uffe2\007\uffe2\012\uffe2\016" +
    "\uffe2\041\uffe2\044\uffe2\046\uffe2\001\002\000\024\004\011" +
    "\005\016\006\017\007\012\012\035\016\026\041\216\044" +
    "\042\046\036\001\002\000\024\004\uffae\005\uffae\006\uffae" +
    "\007\uffae\012\uffae\016\uffae\041\uffae\044\uffae\046\uffae\001" +
    "\002\000\012\031\222\033\220\037\ufff4\040\223\001\002" +
    "\000\004\047\233\001\002\000\004\037\232\001\002\000" +
    "\004\032\225\001\002\000\010\045\057\052\046\053\053" +
    "\001\002\000\004\037\ufff5\001\002\000\004\042\226\001" +
    "\002\000\024\004\uffe9\005\uffe9\006\uffe9\007\uffe9\012\uffe9" +
    "\016\uffe9\041\uffe9\044\uffe9\046\uffe9\001\002\000\024\004" +
    "\uffe2\005\uffe2\006\uffe2\007\uffe2\012\uffe2\016\uffe2\041\uffe2" +
    "\044\uffe2\046\uffe2\001\002\000\024\004\011\005\016\006" +
    "\017\007\012\012\035\016\026\041\231\044\042\046\036" +
    "\001\002\000\020\002\uffe8\003\uffe8\004\uffe8\005\uffe8\006" +
    "\uffe8\007\uffe8\043\uffe8\001\002\000\020\002\ufff9\003\ufff9" +
    "\004\ufff9\005\ufff9\006\ufff9\007\ufff9\043\ufff9\001\002\000" +
    "\004\034\234\001\002\000\006\033\123\037\ufff7\001\002" +
    "\000\004\037\236\001\002\000\020\002\ufff8\003\ufff8\004" +
    "\ufff8\005\ufff8\006\ufff8\007\ufff8\043\ufff8\001\002\000\004" +
    "\037\241\001\002\000\004\002\000\001\002\000\006\002" +
    "\uffff\003\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\237\000\006\004\004\014\003\001\001\000\002\001" +
    "\001\000\014\005\014\006\012\011\006\042\005\051\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\053\023\001\001\000\004\012\024\001" +
    "\001\000\022\002\031\013\027\015\032\017\040\032\030" +
    "\037\036\046\033\051\026\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\024\053\030\044\036\055\047" +
    "\051\050\050\001\001\000\002\001\001\000\010\024\075" +
    "\030\044\050\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\024\073\030\044\050\050" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\024\071\030\044\050\050\001" +
    "\001\000\010\024\070\030\044\050\050\001\001\000\010" +
    "\024\067\030\044\050\050\001\001\000\002\001\001\000" +
    "\010\024\066\030\044\050\050\001\001\000\010\024\065" +
    "\030\044\050\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\030\106\033\107" +
    "\050\050\001\001\000\020\003\101\024\104\030\044\032" +
    "\102\036\055\047\103\050\050\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\035\112\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\030\113\036\055\047\114\050" +
    "\050\001\001\000\002\001\001\000\004\035\116\001\001" +
    "\000\004\035\115\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\043\121\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\020\134\021\133\023\126\030\127\046\131" +
    "\050\050\001\001\000\004\022\176\001\001\000\002\001" +
    "\001\000\012\023\155\030\127\046\131\050\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\054\137\001\001" +
    "\000\004\012\140\001\001\000\024\002\031\013\027\015" +
    "\032\017\040\032\030\037\036\046\033\051\026\055\141" +
    "\001\001\000\002\001\001\000\004\016\144\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\056\146\001\001" +
    "\000\004\012\147\001\001\000\022\002\031\013\027\015" +
    "\032\017\040\032\030\037\036\046\033\051\026\001\001" +
    "\000\002\001\001\000\016\020\154\021\133\023\126\030" +
    "\127\046\131\050\050\001\001\000\016\020\153\021\133" +
    "\023\126\030\127\046\131\050\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\022\157\001\001\000\016" +
    "\023\174\030\127\036\055\046\131\047\175\050\050\001" +
    "\001\000\002\001\001\000\012\023\172\030\127\046\131" +
    "\050\050\001\001\000\016\023\170\030\127\036\055\046" +
    "\131\047\171\050\050\001\001\000\012\023\167\030\127" +
    "\046\131\050\050\001\001\000\012\023\166\030\127\046" +
    "\131\050\050\001\001\000\012\023\165\030\127\046\131" +
    "\050\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\003\200\024\104\030\044" +
    "\032\102\036\055\047\103\050\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\003\206\024\104\030\044\032" +
    "\102\036\055\047\103\050\050\001\001\000\002\001\001" +
    "\000\016\020\210\021\133\023\126\030\127\046\131\050" +
    "\050\001\001\000\002\001\001\000\004\057\212\001\001" +
    "\000\002\001\001\000\004\012\214\001\001\000\022\002" +
    "\031\013\027\015\032\017\040\032\030\037\036\046\033" +
    "\051\026\001\001\000\002\001\001\000\004\010\220\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\036\055\047\223\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\052\226\001\001\000\004\012\227" +
    "\001\001\000\022\002\031\013\027\015\032\017\040\032" +
    "\030\037\036\046\033\051\026\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\043\234\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




Yylex analizadorLexico;

public static void main(String[] argv){
	if (argv.length == 0) {
		      System.out.println("Uso : java Parser  <inputfile)>");
		    }
	else{
	try {
		TablaSimbolos tabla = new TablaSimbolos();
		java.io.FileInputStream stream = new java.io.FileInputStream(argv[0]);
	    java.io.Reader reader = new java.io.InputStreamReader(stream);
		Yylex analizadorLexico= new Yylex(reader,tabla);
		Parser parserObj = new Parser();
		parserObj.analizadorLexico=analizadorLexico;
		parserObj.setScanner(parserObj.analizadorLexico);
		parserObj.parse();
		}
		catch(Exception x) {
		System.out.println("Error fatal."+x.toString());
		}
	}
}

public void error_sintactico(Symbol current_token){
  report_error("Error de sintaxis: linea "+analizadorLexico.linea()+" columna "+analizadorLexico.columna(),current_token);
  
}





/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {


      private  int vtemporal=0;
      public  String nuevaTemporal()
      {
      	return "tmp"+(++vtemporal);
      }
      private  int etiqActual=0;
      public  String nuevaEtiqueta()
      {
      	return "etiqCP_"+(++etiqActual);
      }
      class BloqueCondicion {
	 String etqCierto, etqFalso,codigo;
	 }
	 private BloqueCondicion generarCondicion(String condicion)
	 {
	 BloqueCondicion bCond=new BloqueCondicion();
	 bCond.etqCierto=nuevaEtiqueta();
	 bCond.etqFalso=nuevaEtiqueta();
	 bCond.codigo="if_false,"+condicion+","+bCond.etqFalso+";\ngoto,"+bCond.etqCierto+";\n";
	 return bCond;
	 }
	 
      

  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= listaDeclaraciones 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("Código generado:\n" + l.codigo); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= programa error PTOYCOMA 
            {
              Object RESULT =null;
		 this.parser.error_sintactico(this.parser.cur_token);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listaDeclaraciones ::= listaDeclaraciones DeclaracionVar 
            {
              Sentencia RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia d = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 

					RESULT=new Sentencia(l.codigo+""+d.codigo,"");
					 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // listaDeclaraciones ::= listaDeclaraciones DeclaracionFuncion 
            {
              Sentencia RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int dfleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dfright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia df = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
					System.out.println("DECLARACION FUNCION:"+df.codigo);
					RESULT=new Sentencia(l.codigo+""+df.codigo,"");
					 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // listaDeclaraciones ::= 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("",""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // DeclaracionVar ::= DeclaracionTipoBasico 
            {
              Sentencia RESULT =null;
		int d1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int d1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia d1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
					
					
					RESULT=new Sentencia(d1.codigo,d1.resultado);
					 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionVar",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // DeclaracionVar ::= DeclaracionArr 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionVar",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // DeclaracionTipoBasico ::= Tipo ID AsignacionDecl PTOYCOMA 
            {
              Sentencia RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia a = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 Sentencia resultSent=new Sentencia(s.nombre+"="+a.resultado+"\n",s.nombre);
								RESULT=resultSent;
								s.valor=a.resultado;
								if(a.codigo != "None"){
									s.tipo = t.resultado;							
									if(a.codigo == s.tipo){
										System.out.println("Va bien");
									}else{
										report_fatal_error("ERROR:la asignacion no se corresponde al tipo declarado",this.parser.cur_token);
										
									}
								}
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									}else{
										report_fatal_error("Variable ya declarada",this.parser.cur_token);									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionTipoBasico",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // DeclaracionArr ::= Tipo ID ABRECOR NUM CIERRACOR DOSdim PTOYCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionArr",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DOSdim ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DOSdim",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DOSdim ::= ABRECOR DIM CIERRACOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DOSdim",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // AsignacionDecl ::= ASIG Valores 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=new Sentencia(v.codigo,v.resultado); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsignacionDecl",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // AsignacionDecl ::= 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("None","None"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsignacionDecl",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Valores ::= CARACTER 
            {
              Sentencia RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
  System.out.println("Entro en caracter");
RESULT=new Sentencia("char",c); 
  System.out.println("Salgo en caracter");


              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Valores",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Valores ::= Bool_value 
            {
              Sentencia RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia b = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=new Sentencia("bool",b.resultado); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Valores",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Numeros ::= NUM 
            {
              Sentencia RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Sentencia s =new Sentencia("int",n.toString()); 
	s.tipo  = "int";
	RESULT = s;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Numeros",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Numeros ::= NUMREAL 
            {
              Sentencia RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Float n = (Float)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Sentencia s =new Sentencia("real",n.toString()); 
	s.tipo  = "real";
	RESULT = s;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Numeros",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Bool_value ::= TRUE 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("bool","True"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Bool_value",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Bool_value ::= FALSE 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("bool","False"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Bool_value",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Tipo ::= INTEGER 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("","int"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Tipo ::= REAL 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("","real"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Tipo ::= CHAR 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("","char"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Tipo ::= BOOLEAN 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("","bool"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$0 ::= 
            {
              Sentencia RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
 
								Simbolo sAux;

	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									System.out.println("Insertando "+sAux.nombre);
									}
			this.parser.analizadorLexico.getTabla().set(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",40, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DeclaracionFuncion ::= Tipo ID ABREPAR CIERRAPAR ABRELLAVE NT$0 ListaSentencias CIERRALLAVE 
            {
              Sentencia RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Sentencia) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia ls = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
			 this.parser.analizadorLexico.getTabla().reset();
			 Sentencia resultSent=new Sentencia("def "+s.nombre+"():\n"+ls.codigo,s.nombre);
			 RESULT=resultSent;
			 
			 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionFuncion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NT$1 ::= 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
 
								Simbolo sAux;

	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									System.out.println("Insertando "+sAux.nombre);
									}
			this.parser.analizadorLexico.getTabla().set(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$1",41, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // DeclaracionFuncion ::= VOID ID ABREPAR CIERRAPAR ABRELLAVE NT$1 ListaSentencias CIERRALLAVE 
            {
              Sentencia RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Sentencia) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia ls = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
			 this.parser.analizadorLexico.getTabla().reset();
			 Sentencia resultSent=new Sentencia("def "+s.nombre+"():\n"+ls.codigo,s.nombre);
			 RESULT=resultSent;
			 
			 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionFuncion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ReturnSentencia ::= RETURN ExpresionNum PTOYCOMA 
            {
              Sentencia RESULT =null;
		int exprnumleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int exprnumright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia exprnum = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT=new Sentencia("return "+exprnum.codigo+"\n",""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ReturnSentencia",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ReturnSentencia ::= RETURN Valores PTOYCOMA 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT=new Sentencia("return "+v.resultado+"\n",""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ReturnSentencia",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ListaSentencias ::= ListaSentencias Sentence 
            {
              Sentencia RESULT =null;
		int ls1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ls1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia ls1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia s = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		System.out.println("Entro aqui: sentencia NO vacia:");
RESULT=new Sentencia(ls1.codigo+"\t"+s.codigo,""); 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaSentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ListaSentencias ::= 
            {
              Sentencia RESULT =null;
		
RESULT=new Sentencia("",""); 
System.out.println("Entro aqui: sentencia vacia");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaSentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Sentence ::= Asignacion PTOYCOMA 
            {
              Sentencia RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia a = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
RESULT=new Sentencia(a.codigo,""); 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Sentence ::= LlamadaFunc PTOYCOMA 
            {
              Sentencia RESULT =null;
		int lFuncleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lFuncright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia lFunc = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
RESULT=new Sentencia(lFunc.codigo,""); 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Sentence ::= SenteicaIf 
            {
              Sentencia RESULT =null;
		int sifleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sifright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia sif = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		RESULT=new Sentencia(sif.codigo,"");  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Sentence ::= SentenciaWhile 
            {
              Sentencia RESULT =null;
		int swleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int swright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia sw = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		RESULT=new Sentencia(sw.codigo,"");  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Sentence ::= ReturnSentencia 
            {
              Sentencia RESULT =null;
		int rsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia rs = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		RESULT=new Sentencia(rs.codigo,"");  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Sentence ::= Tipo ID PTOYCOMA 
            {
              Sentencia RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		System.out.println("entro en asignacion");
	Sentencia resultSent=new Sentencia(s.nombre+"=None\n",s.nombre);
								RESULT=resultSent;
								s.valor="None";
								
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									}else{
									report_fatal_error("Variable ya declarada",this.parser.cur_token);
									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Asignacion ::= Tipo ID ASIG AsigTipo 
            {
              Sentencia RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int asleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int asright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia as = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
System.out.println("entro en asignacion");
Sentencia resultSent=new Sentencia(s.nombre+"="+as.resultado+"\n",s.nombre);
								RESULT=resultSent;
								s.valor=as.resultado;
								s.tipo = t.resultado;
								System.out.println(as.tipo+ s.tipo);
									if (as.tipo == "both" && (s.tipo == "int" || s.tipo == "real")){
											System.out.println("Va bien");

									}else if(as.tipo == "int" && s.tipo == "real"){
										System.out.println("Todo ok");
									}else{
										if(as.tipo == s.tipo){
											System.out.println("Va bien");
										}else{
											report_fatal_error("ERROR en asignacion",this.parser.cur_token);
										}
									}
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									}else{
									report_fatal_error("Variable ya declarada",this.parser.cur_token);
									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Asignacion",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Asignacion ::= ID ASIG AsigTipo 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int asleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int asright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia as = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
								
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									report_fatal_error("Variable no inicializada",this.parser.cur_token);
									
									}else{
									 Sentencia resultSent=new Sentencia(s.nombre+"="+as.resultado+"\n",s.nombre);
								RESULT=resultSent;
								s.valor=as.resultado;
									sAux.valor=as.resultado;
									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Asignacion",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Asignacion ::= ArrElement ASIG AsigTipo 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Asignacion",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // ArrElement ::= ID ABRECOR NUM CIERRACOR DOSdim 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ArrElement",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // AsigTipo ::= ExpresionNum 
            {
              Sentencia RESULT =null;
		int exprnleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprnright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprn = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		

Sentencia s = new Sentencia(exprn.codigo,exprn.codigo);
s.tipo =  exprn.tipo;
RESULT = s;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsigTipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // AsigTipo ::= LlamadaFunc 
            {
              Sentencia RESULT =null;
		int lFleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lFright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lF = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
RESULT = new Sentencia(lF.codigo,lF.codigo);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsigTipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // AsigTipo ::= Valores 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
  System.out.println("Entro en asig tipo valores");
RESULT = new Sentencia(v.resultado,v.resultado);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsigTipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Elemento ::= Numeros 
            {
              Sentencia RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia num = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	Sentencia s =new Sentencia("",num.resultado);
	s.tipo  = num.tipo;
	RESULT = s;
	
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Elemento",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Elemento ::= ID 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		Simbolo sAux;
  	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
  	if ((sAux=tabla.buscarGlobal(s.nombre))==null){
		report_fatal_error("Variable no inicializada",this.parser.cur_token);
	}
									
										
   Sentencia sent=new Sentencia("",sAux.nombre);
   sent.tipo = sAux.tipo; 
	RESULT = sent;
	
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Elemento",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // ExpresionNum ::= ExpresionNum MAS ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();
		
	Sentencia resultSent= new Sentencia(e1.codigo+"+"+e2.codigo,temporal);
	resultSent.tipo = "both";
	
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // ExpresionNum ::= ExpresionNum MENOS ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"-"+e2.codigo,temporal);
	resultSent.tipo = "both";

	
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ExpresionNum ::= ExpresionNum MULT ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"*"+e2.codigo,temporal);
	resultSent.tipo = "both";

	
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // ExpresionNum ::= ExpresionNum DIV ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"/"+e2.codigo,temporal);

	resultSent.tipo = "both";
	
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // ExpresionNum ::= ExpresionNum MOD ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"%"+e2.codigo,temporal);
	if(e1.tipo != "int" || e2.tipo != "int"){
		report_fatal_error("Operacion no soportada",this.parser.cur_token);
	}
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // ExpresionNum ::= Elemento 
            {
              Sentencia RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia el = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Sentencia s =new Sentencia(el.resultado,el.resultado);
	s.tipo = el.tipo;
	RESULT = s;
 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // ExpresionNum ::= MENOS ExpresionNum 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia("-"+e.codigo,temporal);
		resultSent.tipo = "both";
	
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ExpresionNum ::= ABREPAR ExpresionNum CIERRAPAR 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia e = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia("("+e.codigo+")",temporal);
		resultSent.tipo = "both";
	
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // LlamadaFunc ::= ID ABREPAR ListaParam CIERRAPAR 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
	Simbolo sAux;
	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
  	if ((sAux=tabla.buscarGlobal(s.nombre))==null){
		report_fatal_error("Variable no inicializada",this.parser.cur_token);
	}
	Sentencia resultSent= new Sentencia(s.nombre+"("+l.codigo+")\n","");
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LlamadaFunc",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ListaParam ::= Elemento ListaParam_p 
            {
              Sentencia RESULT =null;
		int elemleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int elemright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia elem = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
	Sentencia resultSent= new Sentencia(elem.resultado+lp.codigo,"");
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // ListaParam ::= 
            {
              Sentencia RESULT =null;
		
	RESULT = new Sentencia("","");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // ListaParam_p ::= 
            {
              Sentencia RESULT =null;
		
	RESULT = new Sentencia("","");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam_p",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // ListaParam_p ::= COMA Elemento ListaParam_p 
            {
              Sentencia RESULT =null;
		int elemleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int elemright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia elem = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lp1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
	
	RESULT = new Sentencia(","+elem.resultado+lp1.codigo,"");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam_p",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // ListaParam_p ::= COMA Valores ListaParam_p 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lp1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia(","+v.resultado+lp1.codigo,"");
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam_p",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // ListaExprLogicas ::= ExprLogica AND ListaExprLogicas 
            {
              Sentencia RESULT =null;
		int ex_logica1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int ex_logica1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia ex_logica1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int l_expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int l_expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia l_exp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= new Sentencia(ex_logica1.codigo +" and "+l_exp.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaExprLogicas",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // ListaExprLogicas ::= ExprLogica OR ListaExprLogicas 
            {
              Sentencia RESULT =null;
		int ex_logica1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int ex_logica1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia ex_logica1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int l_expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int l_expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia l_exp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT= new Sentencia(ex_logica1.codigo +" or "+l_exp.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaExprLogicas",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // ListaExprLogicas ::= ExprLogica 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
 	System.out.println("Analizo expresion logica");
 	RESULT= new Sentencia(e.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaExprLogicas",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // ExprLogica ::= Expr TipoExpr 
            {
              Sentencia RESULT =null;
		int exprlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int exprlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia exprl = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tipo_exprleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tipo_exprright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia tipo_expr = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia(exprl.codigo+tipo_expr.codigo ,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExprLogica",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // ExprLogica ::= ABREPAR Expr TipoExpr CIERRAPAR 
            {
              Sentencia RESULT =null;
		int exprlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int exprlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia exprl = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int tipo_exprleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tipo_exprright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia tipo_expr = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExprLogica",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // TipoExpr ::= EQUAL Expr 
            {
              Sentencia RESULT =null;
		int exprl1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprl1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprl1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia("=="+exprl1.codigo,"");
 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // TipoExpr ::= NOT_EQUAL Expr 
            {
              Sentencia RESULT =null;
		int exprl1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprl1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprl1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia("!="+exprl1.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // TipoExpr ::= BIGGER Expr 
            {
              Sentencia RESULT =null;
		int exprl1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprl1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprl1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia(">"+exprl1.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // TipoExpr ::= BIGGER_EQUAL Expr 
            {
              Sentencia RESULT =null;
		int exprl1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprl1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprl1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia(">="+exprl1.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // TipoExpr ::= SMALLER Expr 
            {
              Sentencia RESULT =null;
		int exprl1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprl1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprl1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia("<"+exprl1.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // TipoExpr ::= SMALLER_EQUAL Expr 
            {
              Sentencia RESULT =null;
		int exprl1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprl1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprl1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia("<="+exprl1.codigo,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // TipoExpr ::= NOT_EQUAL Valores 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia("!="+v.resultado,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // TipoExpr ::= EQUAL Valores 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
			RESULT = new Sentencia("=="+v.resultado,""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // Expr ::= ArrElement 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // Expr ::= Elemento 
            {
              Sentencia RESULT =null;
		int elemtoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int elemtoright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia elemto = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  	RESULT = new Sentencia(elemto.resultado,"");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // NT$2 ::= 
            {
              Sentencia RESULT =null;
		int l_expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int l_expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia l_exp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
this.parser.analizadorLexico.getTabla().set();
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$2",42, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // NT$3 ::= 
            {
              Sentencia RESULT =(Sentencia) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int l_expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int l_expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Sentencia l_exp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia ls = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
this.parser.analizadorLexico.getTabla().reset();
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$3",43, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // SenteicaIf ::= IF ABREPAR ListaExprLogicas CIERRAPAR ABRELLAVE NT$2 ListaSentencias NT$3 CIERRALLAVE SentenciaElse 
            {
              Sentencia RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Sentencia) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int l_expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int l_expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Sentencia l_exp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Sentencia ls = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int seleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int seright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia se = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
	ls.codigo = ls.codigo.replace("\n", "\n\t");
	String codigo =  "if("+l_exp.codigo+"):\n\t"+ls.codigo+se.codigo;
	RESULT = new Sentencia(codigo+"\n","");

	
	
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SenteicaIf",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // SentenciaElse ::= 
            {
              Sentencia RESULT =null;
			System.out.println("Entro en sentencia else");
	RESULT = new Sentencia("","");
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SentenciaElse",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // NT$4 ::= 
            {
              Sentencia RESULT =null;
this.parser.analizadorLexico.getTabla().set();
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$4",44, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // SentenciaElse ::= ELSE ABRELLAVE NT$4 ListaSentencias CIERRALLAVE 
            {
              Sentencia RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Sentencia) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia ls = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
	
	this.parser.analizadorLexico.getTabla().reset();
	ls.codigo = ls.codigo.replace("\n", "\n\t");
		
	String codigo =  "else:\n\t"+ls.codigo;
	RESULT = new Sentencia(codigo+"\n","");

	
	
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SentenciaElse",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // NT$5 ::= 
            {
              Sentencia RESULT =null;
		int l_expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int l_expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l_exp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
this.parser.analizadorLexico.getTabla().set();
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$5",45, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // SentenciaWhile ::= WHILE ABREPAR ListaExprLogicas CIERRAPAR NT$5 ABRELLAVE ListaSentencias CIERRALLAVE 
            {
              Sentencia RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Sentencia) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int l_expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int l_expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Sentencia l_exp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia ls = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
			this.parser.analizadorLexico.getTabla().reset();
	ls.codigo = ls.codigo.replace("\n", "\n\t");
	String codigo =  "while("+l_exp.codigo+"):\n\t"+ls.codigo;
	RESULT = new Sentencia(codigo+"\n","");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SentenciaWhile",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // listaargumentos ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // listaargumentos ::= ID DOSPUNTOS Tipo listaargumentos_p 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo id = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=l;
			/* Se busca en tabla de simbolos y se inserta o devuelve error*/
			
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // listaargumentos_p ::= 
            {
              Object RESULT =null;
		 
			
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos_p",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // listaargumentos_p ::= COMA ID DOSPUNTOS Tipo listaargumentos_p 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo id = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia a = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=a;
			/* Se busca en tabla de simbolos y se inserta o devuelve error*/
			
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos_p",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
