
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\124\000\002\014\003\000\002\002\004\000\002\014" +
    "\005\000\002\004\004\000\002\004\004\000\002\004\002" +
    "\000\002\005\003\000\002\005\003\000\002\006\005\000" +
    "\002\007\004\000\002\007\006\000\002\041\011\000\002" +
    "\042\002\000\002\042\005\000\002\010\004\000\002\010" +
    "\002\000\002\047\003\000\002\047\003\000\002\050\003" +
    "\000\002\050\003\000\002\036\003\000\002\036\003\000" +
    "\002\051\003\000\002\051\003\000\002\051\003\000\002" +
    "\051\003\000\002\052\002\000\002\011\012\000\002\011" +
    "\012\000\002\044\005\000\002\044\005\000\002\012\004" +
    "\000\002\012\002\000\002\013\004\000\002\013\004\000" +
    "\002\013\003\000\002\013\003\000\002\013\003\000\002" +
    "\002\006\000\002\002\005\000\002\002\005\000\002\046" +
    "\007\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\030\003\000\002\030\003\000\002\024\005\000" +
    "\002\024\005\000\002\024\005\000\002\024\005\000\002" +
    "\024\005\000\002\024\003\000\002\024\004\000\002\024" +
    "\005\000\002\032\006\000\002\033\004\000\002\033\002" +
    "\000\002\035\002\000\002\035\005\000\002\035\005\000" +
    "\002\020\005\000\002\020\005\000\002\020\003\000\002" +
    "\021\004\000\002\021\006\000\002\022\004\000\002\022" +
    "\004\000\002\022\004\000\002\022\004\000\002\022\004" +
    "\000\002\022\004\000\002\022\004\000\002\022\004\000" +
    "\002\023\003\000\002\023\003\000\002\015\012\000\002" +
    "\016\002\000\002\016\006\000\002\017\011\000\002\037" +
    "\002\000\002\037\006\000\002\040\002\000\002\040\007" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\020\002\ufffc\003\ufffc\004\ufffc\005\ufffc\006" +
    "\ufffc\007\ufffc\043\ufffc\001\002\000\006\002\237\003\236" +
    "\001\002\000\020\002\001\003\001\004\011\005\016\006" +
    "\017\007\012\043\014\001\002\000\020\002\ufffa\003\ufffa" +
    "\004\ufffa\005\ufffa\006\ufffa\007\ufffa\043\ufffa\001\002\000" +
    "\020\002\ufffd\003\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd" +
    "\043\ufffd\001\002\000\004\046\212\001\002\000\004\046" +
    "\uffeb\001\002\000\004\046\uffe8\001\002\000\020\002\ufffb" +
    "\003\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb\043\ufffb\001" +
    "\002\000\004\046\020\001\002\000\020\002\ufffe\003\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\043\ufffe\001\002\000" +
    "\004\046\uffea\001\002\000\004\046\uffe9\001\002\000\004" +
    "\031\021\001\002\000\004\032\022\001\002\000\004\042" +
    "\023\001\002\000\022\004\uffe1\005\uffe1\006\uffe1\007\uffe1" +
    "\012\uffe1\016\uffe1\044\uffe1\046\uffe1\001\002\000\022\004" +
    "\011\005\016\006\017\007\012\012\034\016\025\044\040" +
    "\046\035\001\002\000\004\031\204\001\002\000\004\046" +
    "\201\001\002\000\004\037\200\001\002\000\024\004\uffe2" +
    "\005\uffe2\006\uffe2\007\uffe2\012\uffe2\016\uffe2\041\uffe2\044" +
    "\uffe2\046\uffe2\001\002\000\024\004\uffde\005\uffde\006\uffde" +
    "\007\uffde\012\uffde\016\uffde\041\uffde\044\uffde\046\uffde\001" +
    "\002\000\004\037\177\001\002\000\004\040\175\001\002" +
    "\000\004\031\125\001\002\000\010\031\053\033\052\040" +
    "\054\001\002\000\024\004\uffdc\005\uffdc\006\uffdc\007\uffdc" +
    "\012\uffdc\016\uffdc\041\051\044\uffdc\046\uffdc\001\002\000" +
    "\024\004\uffdd\005\uffdd\006\uffdd\007\uffdd\012\uffdd\016\uffdd" +
    "\041\uffdd\044\uffdd\046\uffdd\001\002\000\012\045\046\046" +
    "\041\052\044\053\045\001\002\000\004\037\050\001\002" +
    "\000\014\010\ufff0\011\ufff0\032\ufff0\036\ufff0\037\ufff0\001" +
    "\002\000\004\037\047\001\002\000\014\010\uffed\011\uffed" +
    "\032\uffed\036\uffed\037\uffed\001\002\000\014\010\uffec\011" +
    "\uffec\032\uffec\036\uffec\037\uffec\001\002\000\014\010\ufff1" +
    "\011\ufff1\032\ufff1\036\ufff1\037\ufff1\001\002\000\024\004" +
    "\uffe3\005\uffe3\006\uffe3\007\uffe3\012\uffe3\016\uffe3\041\uffe3" +
    "\044\uffe3\046\uffe3\001\002\000\024\004\uffe4\005\uffe4\006" +
    "\uffe4\007\uffe4\012\uffe4\016\uffe4\041\uffe4\044\uffe4\046\uffe4" +
    "\001\002\000\020\002\uffe5\003\uffe5\004\uffe5\005\uffe5\006" +
    "\uffe5\007\uffe5\043\uffe5\001\002\000\004\047\117\001\002" +
    "\000\004\032\uffc8\001\002\000\022\020\057\031\063\045" +
    "\046\046\067\047\056\051\062\052\044\053\045\001\002" +
    "\000\004\037\uffda\001\002\000\040\010\uffef\011\uffef\014" +
    "\uffef\015\uffef\017\uffef\020\uffef\021\uffef\022\uffef\023\uffef" +
    "\025\uffef\026\uffef\027\uffef\030\uffef\032\uffef\037\uffef\001" +
    "\002\000\014\020\057\031\063\046\075\047\056\051\062" +
    "\001\002\000\020\017\uffcd\020\uffcd\021\uffcd\022\uffcd\023" +
    "\uffcd\032\uffcd\037\uffcd\001\002\000\004\037\uffd6\001\002" +
    "\000\040\010\uffee\011\uffee\014\uffee\015\uffee\017\uffee\020" +
    "\uffee\021\uffee\022\uffee\023\uffee\025\uffee\026\uffee\027\uffee" +
    "\030\uffee\032\uffee\037\uffee\001\002\000\014\020\057\031" +
    "\063\046\075\047\056\051\062\001\002\000\040\010\uffd4" +
    "\011\uffd4\014\uffd4\015\uffd4\017\uffd4\020\uffd4\021\uffd4\022" +
    "\uffd4\023\uffd4\025\uffd4\026\uffd4\027\uffd4\030\uffd4\032\uffd4" +
    "\037\uffd4\001\002\000\004\037\uffd5\001\002\000\016\017" +
    "\071\020\073\021\072\022\074\023\070\037\uffd7\001\002" +
    "\000\020\017\uffd3\020\uffd3\021\uffd3\022\uffd3\023\uffd3\031" +
    "\053\037\uffd3\001\002\000\014\020\057\031\063\046\075" +
    "\047\056\051\062\001\002\000\014\020\057\031\063\046" +
    "\075\047\056\051\062\001\002\000\014\020\057\031\063" +
    "\046\075\047\056\051\062\001\002\000\014\020\057\031" +
    "\063\046\075\047\056\051\062\001\002\000\014\020\057" +
    "\031\063\046\075\047\056\051\062\001\002\000\020\017" +
    "\uffd3\020\uffd3\021\uffd3\022\uffd3\023\uffd3\032\uffd3\037\uffd3" +
    "\001\002\000\020\017\uffcf\020\uffcf\021\uffcf\022\uffcf\023" +
    "\uffcf\032\uffcf\037\uffcf\001\002\000\020\017\uffd1\020\uffd1" +
    "\021\072\022\074\023\070\032\uffd1\037\uffd1\001\002\000" +
    "\020\017\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\032\uffd0" +
    "\037\uffd0\001\002\000\020\017\uffd2\020\uffd2\021\072\022" +
    "\074\023\070\032\uffd2\037\uffd2\001\002\000\020\017\uffce" +
    "\020\uffce\021\uffce\022\uffce\023\uffce\032\uffce\037\uffce\001" +
    "\002\000\016\017\071\020\073\021\072\022\074\023\070" +
    "\032\104\001\002\000\020\017\uffcb\020\uffcb\021\uffcb\022" +
    "\uffcb\023\uffcb\032\uffcb\037\uffcb\001\002\000\020\017\uffcc" +
    "\020\uffcc\021\072\022\074\023\070\032\uffcc\037\uffcc\001" +
    "\002\000\006\032\uffc7\036\111\001\002\000\004\032\110" +
    "\001\002\000\004\037\uffca\001\002\000\012\045\046\046" +
    "\113\052\044\053\045\001\002\000\004\032\uffc9\001\002" +
    "\000\006\032\uffc7\036\111\001\002\000\006\032\uffc7\036" +
    "\111\001\002\000\004\032\uffc5\001\002\000\004\032\uffc6" +
    "\001\002\000\004\034\120\001\002\000\030\010\ufff5\011" +
    "\ufff5\014\ufff5\015\ufff5\025\ufff5\026\ufff5\027\ufff5\030\ufff5" +
    "\032\ufff5\033\122\040\ufff5\001\002\000\026\010\uffd8\011" +
    "\uffd8\014\uffd8\015\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8" +
    "\032\uffd8\040\uffd8\001\002\000\004\050\123\001\002\000" +
    "\004\034\124\001\002\000\030\010\ufff4\011\ufff4\014\ufff4" +
    "\015\ufff4\025\ufff4\026\ufff4\027\ufff4\030\ufff4\032\ufff4\037" +
    "\ufff4\040\ufff4\001\002\000\012\031\130\046\132\047\056" +
    "\051\062\001\002\000\016\014\157\015\154\025\161\026" +
    "\156\027\160\030\162\001\002\000\024\010\uffb6\011\uffb6" +
    "\014\uffb6\015\uffb6\025\uffb6\026\uffb6\027\uffb6\030\uffb6\032" +
    "\uffb6\001\002\000\010\046\132\047\056\051\062\001\002" +
    "\000\024\010\uffb7\011\uffb7\014\uffb7\015\uffb7\025\uffb7\026" +
    "\uffb7\027\uffb7\030\uffb7\032\uffb7\001\002\000\026\010\uffd3" +
    "\011\uffd3\014\uffd3\015\uffd3\025\uffd3\026\uffd3\027\uffd3\030" +
    "\uffd3\032\uffd3\033\052\001\002\000\010\010\147\011\150" +
    "\032\uffc2\001\002\000\004\032\135\001\002\000\004\042" +
    "\136\001\002\000\024\004\uffe1\005\uffe1\006\uffe1\007\uffe1" +
    "\012\uffe1\016\uffe1\041\uffe1\044\uffe1\046\uffe1\001\002\000" +
    "\024\004\011\005\016\006\017\007\012\012\034\016\025" +
    "\041\141\044\040\046\035\001\002\000\024\004\uffdc\005" +
    "\uffdc\006\uffdc\007\uffdc\012\uffdc\016\uffdc\041\uffdc\044\uffdc" +
    "\046\uffdc\001\002\000\026\004\uffb4\005\uffb4\006\uffb4\007" +
    "\uffb4\012\uffb4\013\142\016\uffb4\041\uffb4\044\uffb4\046\uffb4" +
    "\001\002\000\004\042\144\001\002\000\024\004\uffb5\005" +
    "\uffb5\006\uffb5\007\uffb5\012\uffb5\016\uffb5\041\uffb5\044\uffb5" +
    "\046\uffb5\001\002\000\024\004\uffe1\005\uffe1\006\uffe1\007" +
    "\uffe1\012\uffe1\016\uffe1\041\uffe1\044\uffe1\046\uffe1\001\002" +
    "\000\024\004\011\005\016\006\017\007\012\012\034\016" +
    "\025\041\146\044\040\046\035\001\002\000\024\004\uffb3" +
    "\005\uffb3\006\uffb3\007\uffb3\012\uffb3\016\uffb3\041\uffb3\044" +
    "\uffb3\046\uffb3\001\002\000\012\031\130\046\132\047\056" +
    "\051\062\001\002\000\012\031\130\046\132\047\056\051" +
    "\062\001\002\000\004\032\uffc3\001\002\000\004\032\uffc4" +
    "\001\002\000\016\014\157\015\154\025\161\026\156\027" +
    "\160\030\162\001\002\000\016\045\046\046\132\047\056" +
    "\051\062\052\044\053\045\001\002\000\004\032\171\001" +
    "\002\000\010\046\132\047\056\051\062\001\002\000\016" +
    "\045\046\046\132\047\056\051\062\052\044\053\045\001" +
    "\002\000\010\046\132\047\056\051\062\001\002\000\010" +
    "\046\132\047\056\051\062\001\002\000\010\046\132\047" +
    "\056\051\062\001\002\000\010\010\uffba\011\uffba\032\uffba" +
    "\001\002\000\010\010\uffbd\011\uffbd\032\uffbd\001\002\000" +
    "\010\010\uffbb\011\uffbb\032\uffbb\001\002\000\010\010\uffbf" +
    "\011\uffbf\032\uffbf\001\002\000\010\010\uffb8\011\uffb8\032" +
    "\uffb8\001\002\000\010\010\uffbc\011\uffbc\032\uffbc\001\002" +
    "\000\010\010\uffc0\011\uffc0\032\uffc0\001\002\000\010\010" +
    "\uffbe\011\uffbe\032\uffbe\001\002\000\010\010\uffb9\011\uffb9" +
    "\032\uffb9\001\002\000\010\010\uffc1\011\uffc1\032\uffc1\001" +
    "\002\000\022\020\057\031\063\045\046\046\067\047\056" +
    "\051\062\052\044\053\045\001\002\000\004\037\uffd9\001" +
    "\002\000\024\004\uffe0\005\uffe0\006\uffe0\007\uffe0\012\uffe0" +
    "\016\uffe0\041\uffe0\044\uffe0\046\uffe0\001\002\000\024\004" +
    "\uffdf\005\uffdf\006\uffdf\007\uffdf\012\uffdf\016\uffdf\041\uffdf" +
    "\044\uffdf\046\uffdf\001\002\000\004\040\202\001\002\000" +
    "\022\020\057\031\063\045\046\046\067\047\056\051\062" +
    "\052\044\053\045\001\002\000\004\037\uffdb\001\002\000" +
    "\012\031\130\046\132\047\056\051\062\001\002\000\004" +
    "\032\206\001\002\000\004\042\207\001\002\000\024\004" +
    "\uffe1\005\uffe1\006\uffe1\007\uffe1\012\uffe1\016\uffe1\041\uffe1" +
    "\044\uffe1\046\uffe1\001\002\000\024\004\011\005\016\006" +
    "\017\007\012\012\034\016\025\041\211\044\040\046\035" +
    "\001\002\000\024\004\uffb2\005\uffb2\006\uffb2\007\uffb2\012" +
    "\uffb2\016\uffb2\041\uffb2\044\uffb2\046\uffb2\001\002\000\014" +
    "\031\224\033\222\036\ufff2\037\ufff2\040\220\001\002\000" +
    "\006\036\214\037\215\001\002\000\004\046\216\001\002" +
    "\000\020\002\ufff9\003\ufff9\004\ufff9\005\ufff9\006\ufff9\007" +
    "\ufff9\043\ufff9\001\002\000\010\036\ufff2\037\ufff2\040\220" +
    "\001\002\000\006\036\ufff7\037\ufff7\001\002\000\010\045" +
    "\046\052\044\053\045\001\002\000\006\036\ufff3\037\ufff3" +
    "\001\002\000\004\047\232\001\002\000\006\036\ufff8\037" +
    "\ufff8\001\002\000\004\032\225\001\002\000\004\042\226" +
    "\001\002\000\024\004\uffe7\005\uffe7\006\uffe7\007\uffe7\012" +
    "\uffe7\016\uffe7\041\uffe7\044\uffe7\046\uffe7\001\002\000\024" +
    "\004\uffe1\005\uffe1\006\uffe1\007\uffe1\012\uffe1\016\uffe1\041" +
    "\uffe1\044\uffe1\046\uffe1\001\002\000\024\004\011\005\016" +
    "\006\017\007\012\012\034\016\025\041\231\044\040\046" +
    "\035\001\002\000\020\002\uffe6\003\uffe6\004\uffe6\005\uffe6" +
    "\006\uffe6\007\uffe6\043\uffe6\001\002\000\004\034\233\001" +
    "\002\000\006\033\122\037\ufff5\001\002\000\004\037\235" +
    "\001\002\000\020\002\ufff6\003\ufff6\004\ufff6\005\ufff6\006" +
    "\ufff6\007\ufff6\043\ufff6\001\002\000\004\037\240\001\002" +
    "\000\004\002\000\001\002\000\006\002\uffff\003\uffff\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\006\004\004\014\003\001\001\000\002\001" +
    "\001\000\014\005\014\006\012\011\006\041\005\051\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\212\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\023\001\001\000\022\002" +
    "\031\013\027\015\030\017\036\032\026\044\035\046\032" +
    "\051\025\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\036\041" +
    "\047\042\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\033\106\034\105\001\001" +
    "\000\020\003\054\024\065\030\057\032\060\036\041\047" +
    "\064\050\063\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\024\104\030\057\050\063\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\024\102" +
    "\030\057\050\063\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\024\101" +
    "\030\057\050\063\001\001\000\010\024\100\030\057\050" +
    "\063\001\001\000\010\024\077\030\057\050\063\001\001" +
    "\000\010\024\076\030\057\050\063\001\001\000\010\024" +
    "\075\030\057\050\063\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\035\111\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\036\041\047\113\001\001" +
    "\000\002\001\001\000\004\035\115\001\001\000\004\035" +
    "\114\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\042\120\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\020\133\021\132\023\125\030\126\046\130\050\063\001" +
    "\001\000\004\022\173\001\001\000\002\001\001\000\012" +
    "\023\152\030\126\046\130\050\063\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\136\001\001\000\022\002" +
    "\031\013\027\015\030\017\036\032\026\044\137\046\032" +
    "\051\025\001\001\000\002\001\001\000\004\016\142\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\144" +
    "\001\001\000\022\002\031\013\027\015\030\017\036\032" +
    "\026\044\137\046\032\051\025\001\001\000\002\001\001" +
    "\000\016\020\151\021\132\023\125\030\126\046\130\050" +
    "\063\001\001\000\014\021\150\023\125\030\126\046\130" +
    "\050\063\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\022\154\001\001\000\016\023\171\030\126\036\041" +
    "\046\130\047\172\050\063\001\001\000\002\001\001\000" +
    "\012\023\167\030\126\046\130\050\063\001\001\000\016" +
    "\023\165\030\126\036\041\046\130\047\166\050\063\001" +
    "\001\000\012\023\164\030\126\046\130\050\063\001\001" +
    "\000\012\023\163\030\126\046\130\050\063\001\001\000" +
    "\012\023\162\030\126\046\130\050\063\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\003\175\024\065\030\057\032\060\036\041\047\064" +
    "\050\063\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\003\202\024\065" +
    "\030\057\032\060\036\041\047\064\050\063\001\001\000" +
    "\002\001\001\000\016\020\204\021\132\023\125\030\126" +
    "\046\130\050\063\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\207\001\001\000\022\002\031\013\027" +
    "\015\030\017\036\032\026\044\137\046\032\051\025\001" +
    "\001\000\002\001\001\000\004\010\222\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\216\001\001\000\002\001\001\000\006\036\041\047\220" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\052\226" +
    "\001\001\000\004\012\227\001\001\000\022\002\031\013" +
    "\027\015\030\017\036\032\026\044\137\046\032\051\025" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\042" +
    "\233\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




Yylex analizadorLexico;

public static void main(String[] argv){
	if (argv.length == 0) {
		      System.out.println("Uso : java Parser  <inputfile)>");
		    }
	else{
	try {
		TablaSimbolos tabla = new TablaSimbolos();
		java.io.FileInputStream stream = new java.io.FileInputStream(argv[0]);
	    java.io.Reader reader = new java.io.InputStreamReader(stream);
		Yylex analizadorLexico= new Yylex(reader,tabla);
		Parser parserObj = new Parser();
		parserObj.analizadorLexico=analizadorLexico;
		parserObj.setScanner(parserObj.analizadorLexico);
		parserObj.parse();
		}
		catch(Exception x) {
		System.out.println("Error fatal."+x.toString());
		}
	}
}

public void error_sintactico(Symbol current_token){
  report_error("Error de sintaxis: linea "+analizadorLexico.linea()+" columna "+analizadorLexico.columna(),current_token);
  
}





/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {


      private  int vtemporal=0;
      public  String nuevaTemporal()
      {
      	return "tmp"+(++vtemporal);
      }
      private  int etiqActual=0;
      public  String nuevaEtiqueta()
      {
      	return "etiqCP_"+(++etiqActual);
      }
      class BloqueCondicion {
	 String etqCierto, etqFalso,codigo;
	 }
	 private BloqueCondicion generarCondicion(String condicion)
	 {
	 BloqueCondicion bCond=new BloqueCondicion();
	 bCond.etqCierto=nuevaEtiqueta();
	 bCond.etqFalso=nuevaEtiqueta();
	 bCond.codigo="if_false,"+condicion+","+bCond.etqFalso+";\ngoto,"+bCond.etqCierto+";\n";
	 return bCond;
	 }
	 
      

  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= listaDeclaraciones 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("Código generado:\n" + l.codigo); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= programa error PTOYCOMA 
            {
              Object RESULT =null;
		 this.parser.error_sintactico(this.parser.cur_token);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listaDeclaraciones ::= listaDeclaraciones DeclaracionVar 
            {
              Sentencia RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia d = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 

					RESULT=new Sentencia(l.codigo+""+d.codigo,"");
					 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // listaDeclaraciones ::= listaDeclaraciones DeclaracionFuncion 
            {
              Sentencia RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int dfleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dfright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia df = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
					System.out.println("DECLARACION FUNCION:"+df.codigo);
					RESULT=new Sentencia(l.codigo+""+df.codigo,"");
					 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // listaDeclaraciones ::= 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("",""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaDeclaraciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // DeclaracionVar ::= DeclaracionTipoBasico 
            {
              Sentencia RESULT =null;
		int d1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int d1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia d1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
					
					
					RESULT=new Sentencia(d1.codigo,d1.resultado);
					 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionVar",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // DeclaracionVar ::= DeclaracionArr 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionVar",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // DeclaracionTipoBasico ::= Tipo ListaValores PTOYCOMA 
            {
              Sentencia RESULT =null;
		int l1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int l1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
					RESULT=new Sentencia(l1.codigo, l1.resultado);
					 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionTipoBasico",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ListaValores ::= ID AsignacionDecl 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia a = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Sentencia resultSent=new Sentencia(s.nombre+"="+a.resultado+"\n",s.nombre);
								RESULT=resultSent;
								s.valor=a.resultado;
								
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									}else{
									sAux.valor=a.resultado;
									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaValores",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ListaValores ::= ListaValores COMA ID AsignacionDecl 
            {
              Sentencia RESULT =null;
		int lv1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int lv1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Sentencia lv1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia a = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Sentencia resultSent=new Sentencia(lv1.codigo+s.nombre+"="+a.resultado+"\n",s.nombre);
								RESULT=resultSent;
								s.valor=a.resultado;
								
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									System.out.println("Insertando "+sAux.nombre);
									}else{
									sAux.valor=a.resultado;
									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaValores",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DeclaracionArr ::= Tipo ID ABRECOR NUM CIERRACOR DOSdim PTOYCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionArr",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // DOSdim ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DOSdim",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DOSdim ::= ABRECOR DIM CIERRACOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DOSdim",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // AsignacionDecl ::= ASIG Valores 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsignacionDecl",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // AsignacionDecl ::= 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("","None"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsignacionDecl",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Valores ::= CARACTER 
            {
              Sentencia RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
  System.out.println("Entro en caracter");
RESULT=new Sentencia("",c); 
  System.out.println("Salgo en caracter");


              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Valores",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Valores ::= Bool_value 
            {
              Sentencia RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia b = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=new Sentencia("",b.resultado); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Valores",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Numeros ::= NUM 
            {
              Sentencia RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=new Sentencia("",n.toString()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Numeros",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Numeros ::= NUMREAL 
            {
              Sentencia RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Float n = (Float)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=new Sentencia("",n.toString()); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Numeros",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Bool_value ::= TRUE 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("","True"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Bool_value",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Bool_value ::= FALSE 
            {
              Sentencia RESULT =null;
		 RESULT=new Sentencia("","False"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Bool_value",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Tipo ::= INTEGER 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Tipo ::= REAL 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Tipo ::= CHAR 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Tipo ::= BOOLEAN 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tipo",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NT$0 ::= 
            {
              Sentencia RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
 
								Simbolo sAux;

	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									System.out.println("Insertando "+sAux.nombre);
									}
			this.parser.analizadorLexico.getTabla().set(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",40, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // DeclaracionFuncion ::= Tipo ID ABREPAR CIERRAPAR ABRELLAVE NT$0 ListaSentencias CIERRALLAVE 
            {
              Sentencia RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Sentencia) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia ls = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
			 this.parser.analizadorLexico.getTabla().reset();
			 Sentencia resultSent=new Sentencia("def "+s.nombre+"():\n"+ls.codigo,s.nombre);
			 RESULT=resultSent;
			 
			 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionFuncion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // DeclaracionFuncion ::= VOID ID ABREPAR CIERRAPAR ABRELLAVE ListaSentencias ReturnSentencia CIERRALLAVE 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DeclaracionFuncion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ReturnSentencia ::= RETURN ID PTOYCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ReturnSentencia",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ReturnSentencia ::= RETURN Valores PTOYCOMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ReturnSentencia",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ListaSentencias ::= ListaSentencias Sentence 
            {
              Sentencia RESULT =null;
		int ls1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ls1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia ls1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia s = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		System.out.println("Entro aqui: sentencia NO vacia");
RESULT=new Sentencia(ls1.codigo+"\t"+s.codigo,""); 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaSentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ListaSentencias ::= 
            {
              Sentencia RESULT =null;
		
RESULT=new Sentencia("",""); 
System.out.println("Entro aqui: sentencia vacia");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaSentencias",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Sentence ::= Asignacion PTOYCOMA 
            {
              Sentencia RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia a = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
RESULT=new Sentencia(a.codigo,""); 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Sentence ::= LlamadaFunc PTOYCOMA 
            {
              Sentencia RESULT =null;
		int lFuncleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lFuncright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia lFunc = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
RESULT=new Sentencia(lFunc.codigo,""); 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Sentence ::= SenteicaIf 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Sentence ::= SentenciaWhile 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Sentence ::= ReturnSentencia 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Sentence",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Asignacion ::= Tipo ID ASIG AsigTipo 
            {
              Sentencia RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Sentencia t = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int asleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int asright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia as = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
System.out.println("entro en asignacion");
Sentencia resultSent=new Sentencia(s.nombre+"="+as.resultado+"\n",s.nombre);
								RESULT=resultSent;
								s.valor=as.resultado;
								
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									sAux=tabla.insertar(s);
									}else{
									sAux.valor=as.resultado;
									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Asignacion",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Asignacion ::= ID ASIG AsigTipo 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int asleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int asright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia as = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
								
								Simbolo sAux;
								TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
								if ((sAux=tabla.buscarGlobal(s.nombre))==null)
									{
									report_fatal_error("Variable no inicializada",this.parser.cur_token);
									
									}else{
									 Sentencia resultSent=new Sentencia(s.nombre+"="+as.resultado+"\n",s.nombre);
								RESULT=resultSent;
								s.valor=as.resultado;
									sAux.valor=as.resultado;
									
									}
										
									
									
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Asignacion",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Asignacion ::= ArrElement ASIG AsigTipo 
            {
              Sentencia RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Asignacion",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // ArrElement ::= ID ABRECOR NUM CIERRACOR DOSdim 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ArrElement",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // AsigTipo ::= ExpresionNum 
            {
              Sentencia RESULT =null;
		int exprnleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int exprnright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia exprn = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
RESULT = new Sentencia(exprn.codigo,exprn.codigo);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsigTipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // AsigTipo ::= LlamadaFunc 
            {
              Sentencia RESULT =null;
		int lFleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lFright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lF = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
RESULT = new Sentencia(lF.codigo,lF.codigo);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsigTipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // AsigTipo ::= Valores 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
  System.out.println("Entro en asig tipo valores");
RESULT = new Sentencia(v.resultado,v.resultado);

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AsigTipo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Elemento ::= Numeros 
            {
              Sentencia RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia num = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=new Sentencia("",num.resultado); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Elemento",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Elemento ::= ID 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		Simbolo sAux;
  	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
  	if ((sAux=tabla.buscarGlobal(s.nombre))==null){
		report_fatal_error("Variable no inicializada",this.parser.cur_token);
	}
									
										
   RESULT=new Sentencia("",sAux.nombre); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Elemento",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // ExpresionNum ::= ExpresionNum MAS ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"+"+e2.codigo,temporal);
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // ExpresionNum ::= ExpresionNum MENOS ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"-"+e2.codigo,temporal);
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ExpresionNum ::= ExpresionNum MULT ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"*"+e2.codigo,temporal);
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // ExpresionNum ::= ExpresionNum DIV ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"/"+e2.codigo,temporal);
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // ExpresionNum ::= ExpresionNum MOD ExpresionNum 
            {
              Sentencia RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Sentencia e1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e2 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia(e1.codigo+"%"+e2.codigo,temporal);
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // ExpresionNum ::= Elemento 
            {
              Sentencia RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int elright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia el = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=new Sentencia(el.resultado,el.resultado); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // ExpresionNum ::= MENOS ExpresionNum 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia e = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia("-"+e.codigo,temporal);
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ExpresionNum ::= ABREPAR ExpresionNum CIERRAPAR 
            {
              Sentencia RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia e = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
	String temporal=nuevaTemporal();	
	Sentencia resultSent= new Sentencia("("+e.codigo+")",temporal);
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExpresionNum",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // LlamadaFunc ::= ID ABREPAR ListaParam CIERRAPAR 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
	Simbolo sAux;
	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
  	if ((sAux=tabla.buscarGlobal(s.nombre))==null){
		report_fatal_error("Variable no inicializada",this.parser.cur_token);
	}
	Sentencia resultSent= new Sentencia(s.nombre+"("+l.codigo+")","");
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LlamadaFunc",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ListaParam ::= Elem ListaParam_p 
            {
              Sentencia RESULT =null;
		int elemleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int elemright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia elem = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lp = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
	Sentencia resultSent= new Sentencia("("+elem.codigo+lp.codigo+")","");
	RESULT= resultSent; 

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // ListaParam ::= 
            {
              Sentencia RESULT =null;
		
RESULT = new Sentencia("","");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // ListaParam_p ::= 
            {
              Sentencia RESULT =null;
		
RESULT = new Sentencia("","");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam_p",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // ListaParam_p ::= COMA ID ListaParam_p 
            {
              Sentencia RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Simbolo s = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lp1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
	Simbolo sAux;
  	TablaSimbolos tabla=this.parser.analizadorLexico.getTabla();
  	if ((sAux=tabla.buscarGlobal(s.nombre))==null){
		report_fatal_error("Variable no inicializada",this.parser.cur_token);
	}
	RESULT = new Sentencia(","+s.nombre+lp1.codigo,"");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam_p",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // ListaParam_p ::= COMA Valores ListaParam_p 
            {
              Sentencia RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia v = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lp1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lp1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Sentencia lp1 = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		RESULT = new Sentencia(","+v.resultado+lp1.codigo,"");
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaParam_p",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // ListaExprLogicas ::= ExprLogica AND ListaExprLogicas 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaExprLogicas",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // ListaExprLogicas ::= ExprLogica OR ExprLogica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaExprLogicas",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // ListaExprLogicas ::= ExprLogica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ListaExprLogicas",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // ExprLogica ::= Expr TipoExpr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExprLogica",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // ExprLogica ::= ABREPAR Expr TipoExpr CIERRAPAR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ExprLogica",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // TipoExpr ::= EQUAL Expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // TipoExpr ::= NOT_EQUAL Expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // TipoExpr ::= BIGGER Expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // TipoExpr ::= BIGGER_EQUAL Expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // TipoExpr ::= SMALLER Expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // TipoExpr ::= SMALLER_EQUAL Expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // TipoExpr ::= NOT_EQUAL Valores 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // TipoExpr ::= EQUAL Valores 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TipoExpr",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // Expr ::= ArrElement 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // Expr ::= Elemento 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // SenteicaIf ::= IF ABREPAR ListaExprLogicas CIERRAPAR ABRELLAVE ListaSentencias CIERRALLAVE SentenciaElse 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SenteicaIf",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // SentenciaElse ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SentenciaElse",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // SentenciaElse ::= ELSE ABRELLAVE ListaSentencias CIERRALLAVE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SentenciaElse",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // SentenciaWhile ::= WHILE ABREPAR ListaExprLogicas CIERRAPAR ABRELLAVE ListaSentencias CIERRALLAVE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SentenciaWhile",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // listaargumentos ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // listaargumentos ::= ID DOSPUNTOS Tipo listaargumentos_p 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo id = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia l = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=l;
			/* Se busca en tabla de simbolos y se inserta o devuelve error*/
			
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // listaargumentos_p ::= 
            {
              Object RESULT =null;
		 
			
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos_p",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // listaargumentos_p ::= COMA ID DOSPUNTOS Tipo listaargumentos_p 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Simbolo id = (Simbolo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Sentencia a = (Sentencia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=a;
			/* Se busca en tabla de simbolos y se inserta o devuelve error*/
			
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("listaargumentos_p",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
