
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 28;
  public static final int CIERRALLAVE = 32;
  public static final int MULT = 16;
  public static final int CHAR = 4;
  public static final int NOT_EQUAL = 12;
  public static final int INTEGER = 2;
  public static final int SMALLER = 22;
  public static final int AND = 7;
  public static final int CARACTER = 37;
  public static final int OR = 8;
  public static final int SMALLER_EQUAL = 23;
  public static final int DIV = 17;
  public static final int NUM = 39;
  public static final int PTOYCOMA = 30;
  public static final int IF = 9;
  public static final int UMENOS = 19;
  public static final int ID = 38;
  public static final int DIM = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 35;
  public static final int ASIG = 31;
  public static final int EQUAL = 11;
  public static final int TRUE = 42;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int COMENTARIO = 36;
  public static final int BIGGER_EQUAL = 21;
  public static final int MENOS = 15;
  public static final int CIERRACOR = 27;
  public static final int MOD = 18;
  public static final int BIGGER = 20;
  public static final int VOID = 34;
  public static final int NUMREAL = 41;
  public static final int CIERRAPAR = 25;
  public static final int REAL = 3;
  public static final int ABRECOR = 26;
  public static final int ELSE = 10;
  public static final int ABRELLAVE = 33;
  public static final int READ = 6;
  public static final int ABREPAR = 24;
  public static final int WHILE = 13;
  public static final int FALSE = 43;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "REAL",
  "CHAR",
  "BOOLEAN",
  "READ",
  "AND",
  "OR",
  "IF",
  "ELSE",
  "EQUAL",
  "NOT_EQUAL",
  "WHILE",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "UMENOS",
  "BIGGER",
  "BIGGER_EQUAL",
  "SMALLER",
  "SMALLER_EQUAL",
  "ABREPAR",
  "CIERRAPAR",
  "ABRECOR",
  "CIERRACOR",
  "DOSPUNTOS",
  "COMA",
  "PTOYCOMA",
  "ASIG",
  "CIERRALLAVE",
  "ABRELLAVE",
  "VOID",
  "RETURN",
  "COMENTARIO",
  "CARACTER",
  "ID",
  "NUM",
  "DIM",
  "NUMREAL",
  "TRUE",
  "FALSE"
  };
}

